name=Gralha Azul
version=1.16.0
author=dantiel
maintainer=dantiel
sentence=O Grande Código da Gralha Azul — Ornithopter CRSF/PPM para RP2040 Zero
paragraph=Biblioteca para controlo de ornitóptero com CRSF ou PPM, suporte opcional para BMP180 e NeoPixel
category=Device Control
url=https://github.com/dantiel/o-grande-codigo-da-gralha-azul
architectures=rp2040
includes=GralhaAzul.h
