name=O Grande Código da Gralha Azul
version=1.17.0
author=Dantiel
maintainer=Dantiel
sentence=Ornitóptero CRSF/PPM para RP2040 Zero — Biblioteca do Coração Alado
paragraph=Controlo de asas com CRSF ou PPM, NeoPixel opcional, BMP180 opcional, telemetria CRSF opcional. Configurável por modelo via #define.
category=Device Control
url=https://github.com/dantiel/o-grande-codigo-da-gralha-azul
architectures=rp2040
includes=GralhaAzul.h